// The backend-agnostic chat model + the adapter contract. The kit never talks
// to a backend itself: the host app implements ChatAdapter (Supabase, REST,
// mock…) and the kit renders/orchestrates.

export type MessageDirection = 'in' | 'out';

export type MessageType =
  | 'text'
  | 'image'
  | 'video'
  | 'audio'
  | 'document'
  | 'sticker'
  | 'location'
  | 'contacts'
  | 'template'
  | 'interactive'
  | 'reaction'
  | 'button'
  | 'order'
  | 'system'
  | 'request_welcome'
  | 'unsupported'
  | 'unknown';

export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed' | 'received';

export type MediaInfo = {
  /** none = no binary; pending = arriving; ready = resolvable; failed = gone/broken */
  status: 'none' | 'pending' | 'ready' | 'failed';
  mime?: string | null;
  filename?: string | null;
  sizeBytes?: number | null;
  /** WhatsApp voice note (PTT) vs plain audio file */
  voice?: boolean;
  /** Optional pre-resolved URL; otherwise the kit calls adapter.resolveMediaUrl */
  url?: string | null;
};

export type LocationInfo = {
  latitude: number;
  longitude: number;
  name?: string | null;
  address?: string | null;
};

export type ContactCard = { name: string; phones: string[] };

export type InteractiveInfo = {
  /** Prompt text shown in the bubble */
  text?: string | null;
  /** Options offered (buttons or list rows) */
  options?: { id: string; title: string; description?: string | null }[];
  /** For inbound replies: the option the customer picked */
  selectedTitle?: string | null;
};

export type Reaction = { emoji: string; from: string };

export type ChatMessage = {
  /** Stable unique id (DB row id). Optimistic messages use the clientId here until reconciled. */
  id: string;
  /** Correlation id generated by the kit for optimistic sends. */
  clientId?: string | null;
  /** Provider id (e.g. WhatsApp wamid) — replies and reactions reference this. */
  externalId?: string | null;
  conversationId: string;
  direction: MessageDirection;
  type: MessageType;
  status: MessageStatus;
  /** Flat text projection: body, caption, tapped button title… */
  text: string | null;
  authorName?: string | null;
  /** externalId of the quoted message */
  replyTo?: string | null;
  reactions?: Reaction[];
  media?: MediaInfo | null;
  location?: LocationInfo | null;
  contacts?: ContactCard[] | null;
  interactive?: InteractiveInfo | null;
  template?: { name: string } | null;
  errorMessage?: string | null;
  /** ISO timestamp */
  timestamp: string;
};

export type Conversation = {
  id: string;
  /** Display name (contact profile name → phone fallback is the host's call) */
  title: string;
  phone: string;
  avatarUrl?: string | null;
  lastMessagePreview?: string | null;
  lastMessageType?: MessageType | null;
  lastMessageDirection?: MessageDirection | null;
  lastMessageAt?: string | null;
  unreadCount: number;
  /** WhatsApp 24h customer-service window; null/undefined = unknown */
  sessionExpiresAt?: string | null;
  /** Shown as a small badge when the inbox aggregates several numbers */
  accountLabel?: string | null;
  /**
   * Colour that identifies that number — any CSS colour, a `var(--token)`
   * included. Rendered as a dot on the account badge (list row + thread header).
   */
  accountColor?: string | null;
};

export type SendMessageInput =
  | { kind: 'text'; conversationId: string; text: string; replyTo?: string | null }
  | {
      kind: 'media';
      conversationId: string;
      file: File | Blob;
      mediaType: 'image' | 'video' | 'audio' | 'document';
      caption?: string | null;
      filename?: string | null;
      voice?: boolean;
      replyTo?: string | null;
    }
  | { kind: 'reaction'; conversationId: string; targetExternalId: string; emoji: string };

// Omit must distribute over the union — plain Omit collapses it to common keys.
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;
/** A send before the controller stamps the active conversation id on it. */
export type SendDraft = DistributiveOmit<SendMessageInput, 'conversationId'>;

export type SendMessageResult = {
  /** Backend row id when known (lets the kit reconcile before realtime lands) */
  id?: string | null;
  externalId?: string | null;
};

export type SubscribeHandlers = {
  /** New message row (any direction) */
  onMessage?: (message: ChatMessage) => void;
  /** Updated message row (status upgrade, media ready, reactions) */
  onMessageUpdate?: (message: ChatMessage) => void;
  /** New/updated conversation row (preview, unread, session window) */
  onConversation?: (conversation: Conversation) => void;
};

export type ListMessagesResult = { messages: ChatMessage[]; hasMore: boolean };

export type ChatAdapter = {
  listConversations: (params: { query?: string }) => Promise<Conversation[]>;
  /** Newest page when `before` is null; older pages keyed by the oldest loaded timestamp. */
  listMessages: (params: {
    conversationId: string;
    before?: string | null;
    limit?: number;
  }) => Promise<ListMessagesResult>;
  sendMessage: (input: SendMessageInput) => Promise<SendMessageResult>;
  markRead: (conversationId: string) => Promise<void>;
  /** Signed URL (or null when unavailable). Called lazily per message and cached by the kit. */
  resolveMediaUrl: (message: ChatMessage) => Promise<string | null>;
  /** Live updates. Returns the unsubscribe function. */
  subscribe: (handlers: SubscribeHandlers) => () => void;
  /**
   * Re-send a failed OUTBOUND message. When provided, failed bubbles show a
   * retry button; the backend should re-dispatch and stream the status change
   * back through `subscribe` (same row or a replacement).
   */
  retryMessage?: (message: ChatMessage) => Promise<void>;
};

export function isMediaType(type: MessageType): boolean {
  return (
    type === 'image' ||
    type === 'video' ||
    type === 'audio' ||
    type === 'document' ||
    type === 'sticker'
  );
}
